### ISSUE TITLE
Log beers that was not annonced

### ISSUE THREAD

**Issue by petterl** [jonpacker/cbc-menu#5]
There where some breweries that updated their list live, and then you have some breweries that done even themselves seem to know what they are going to serve.

Maybe add the possibility to add extra brews to a session manually? The breweries never change so only the way to add another beer that you did not know of manually.

The Untappd connection is ok to fail, but atleast a rate and note would be logged.

**Comment by petterl** [comment]
An "Add beer" possibility where you select brewery, Enter a name, note and rating is enough.
Bonus to be able to search for the beer in untappd to get all info.

**Comment by jonpacker** [comment]
Not going to do this. As long as the list in the app is in sync with the official list, I think that is a completely acceptable error rate. Then it is the brewery's fault for not sticking to the list of beers they sent to the organizer. As a user, this happened maybe 8-10 times this year, and it's completely fine with me: I can just open untappd and check them in there.

**Comment by petterl** [comment]
Did you visit Bokeryder? That is the main reason for this. None of their beers ws in the app.

**Comment by jonpacker** [comment]
Bokkereyder is absolutely outside the scope of this app. The reason they did that is because they were rotating beers inside the sessions: in some sessions they had over 10 beers, and it depended on when you queued up on what you got.
