### ISSUE TITLE
See MY rating from untappd

### ISSUE THREAD

**Issue by petterl** [jonpacker/cbc-menu#6]
It would be really cool to see if I have had the beer before and what MY ratings was last time.

After a sucessful connection to untappd, a possibility to fetch ratings from untappd would be very cool. 

And then show in the list:
 - Average rating
 - last rating date

That way you can get a feeling on how your taste has changed.

**Comment by jonpacker** [comment]
This is [already implemented](https://github.com/jonpacker/cbc-menu/blob/29584dd22d08cd12037dd2c45ddd3fa95bf20d90/public/js/cbc.js#L243), but I didn't document it publicly because if you have over 5000 unique it will get you rate-limited immediately. Maybe next year.
