### ISSUE TITLE
Possibility to sort by number

### ISSUE THREAD

**Issue by petterl** [jonpacker/cbc-menu#8]
When going to breweries, it is quite ofteh that you take a beer from the next stand aswell. But in the app you have to scroll up and down to find them.

It would be nice if the breweries had a number as well that match the number on the site. If it would be possible to sort by that you would easily find the ones next to each other.

**Comment by jonpacker** [comment]
I agree that this is a good idea, but this information is not public before the first session starts, and I'm not in the business of trying to do data entry and drink beer at the same time... can reopen if there's some way to get the information ahead of time.
